CREATE TABLE student
(
ID      NUMBER      not null,
Name    VARCHAR2    (40),
PRIMARY KEY (ID)
);

INSERT INTO student (ID , Name) VALUES (12 , 'Richard');
INSERT INTO student (ID , Name) VALUES (69 , 'Jesse');
INSERT INTO student (ID , Name) VALUES (10 , 'Megan');
INSERT INTO student (ID , Name) VALUES (22 , 'Emmett');


CREATE PROFILE ProSDEVUser LIMIT
    PASSWORD_VERIFY_FUNCTION ora12c_strong_verify_function
    SESSIONS_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 4
    PASSWORD_LIFE_TIME 120
    PASSWORD_GRACE_TIME 1/24
    ;

CREATE USER TS1RICHARDBROWN IDENTIFIED BY "QWErtQWErt123@#$"  
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
PROFILE PROSDEVUSER
ACCOUNT unlock;

ALTER USER "TS1RICHARDBROWN" QUOTA 20M ON "USERS";


CREATE ROLE TS1RoleRichardBrown NOT IDENTIFIED;
    
GRANT SELECT ON student to TS1RoleRichardBrown;
GRANT CREATE SESSION to TS1RoleRichardBrown;

GRANT "TS1ROLERICHARDBROWN" TO "TS1RICHARDBROWN" ;


CREATE USER TS2RICHARDBROWN IDENTIFIED BY "QWErtQWErt345#$%"
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
PROFILE PROSDEVUSER
ACCOUNT unlock;

ALTER USER "TS2RICHARDBROWN" QUOTA 20M ON "USERS";

CREATE ROLE TS2ROLERICHARDBROWN NOT IDENTIFIED;

GRANT CREATE SESSION TO TS2ROLERICHARDBROWN;
GRANT SELECT ON Admin.student TO TS2ROLERICHARDBROWN;
GRANT CREATE TABLE TO TS2ROLERICHARDBROWN;

GRANT "TS2ROLERICHARDBROWN" TO "TS2RICHARDBROWN";




